FROM node:16.15-alpine3.14 as builder
WORKDIR /app
COPY ./package*.json /app/
RUN npm install
COPY . /app

RUN npm run build

FROM nginx:alpine as prod

COPY nginx.conf /etc/nginx/conf.d/default.conf

WORKDIR /usr/share/nginx/html
COPY --from=builder /app/dist .

EXPOSE 8080
CMD [ "nginx", "-g", "daemon off;" ]